[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--black"

# Show live log during testing
# log_cli = true
log_level = "DEBUG"
log_format = "%(asctime)s,%(msecs)3d %(filename)-15s %(lineno)4d %(levelname)-8s %(name)-10s %(message)s"
filterwarnings = [
    "ignore:invalid escape sequence:DeprecationWarning"
]

[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38', 'py39']
